'use client';

import { Loader2, Sparkles } from 'lucide-react';
import { useState } from 'react';

import type { LLMProvider, WorkflowState } from '@rfp-pulse/db';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { workflowStateLabel, workflowStateVariant } from '@/lib/workflow';

export interface QuestionSummary {
  id: string;
  projectId: string;
  projectTitle: string;
  questionText: string;
  sectionPath: string | null;
  state: WorkflowState;
  answer: {
    id: string;
    content: string;
    generatedBy: LLMProvider | null;
    updatedAt: string;
  } | null;
}

export function TaskList({
  initialQuestions,
  accessToken,
  apiBase,
}: {
  initialQuestions: QuestionSummary[];
  accessToken: string;
  apiBase: string;
}): JSX.Element {
  const [questions, setQuestions] = useState<QuestionSummary[]>(initialQuestions);
  const [draftingIds, setDraftingIds] = useState<Set<string>>(new Set());
  const [errorIds, setErrorIds] = useState<Record<string, string>>({});

  async function handleDraft(questionId: string): Promise<void> {
    setDraftingIds((prev) => new Set(prev).add(questionId));
    setErrorIds((prev) => {
      const { [questionId]: _removed, ...rest } = prev;
      return rest;
    });
    try {
      const res = await fetch(`${apiBase}/api/questions/${questionId}/draft`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({}),
      });
      if (!res.ok) {
        throw new Error(`Draft request failed: ${res.status} ${res.statusText}`);
      }
      const updated = (await res.json()) as QuestionSummary;
      setQuestions((prev) => prev.map((q) => (q.id === updated.id ? updated : q)));
    } catch (e) {
      setErrorIds((prev) => ({
        ...prev,
        [questionId]: e instanceof Error ? e.message : 'Unknown error',
      }));
    } finally {
      setDraftingIds((prev) => {
        const next = new Set(prev);
        next.delete(questionId);
        return next;
      });
    }
  }

  if (questions.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Inbox zero</CardTitle>
          <CardDescription>
            You have no questions in the Drafting state. Check back after an RFP upload.
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-4" data-testid="task-list">
      {questions.map((q) => {
        const drafting = draftingIds.has(q.id);
        const error = errorIds[q.id];
        return (
          <Card key={q.id} data-testid={`task-${q.id}`}>
            <CardHeader className="flex flex-row items-start justify-between gap-4">
              <div className="flex flex-col gap-1">
                <CardDescription className="flex items-center gap-2 text-xs">
                  <span>{q.projectTitle}</span>
                  {q.sectionPath && <span>· {q.sectionPath}</span>}
                </CardDescription>
                <CardTitle className="text-base">{q.questionText}</CardTitle>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant={workflowStateVariant(q.state)}>{workflowStateLabel(q.state)}</Badge>
                <Button
                  type="button"
                  size="sm"
                  onClick={() => handleDraft(q.id)}
                  disabled={drafting}
                  data-testid={`draft-button-${q.id}`}
                >
                  {drafting ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      Drafting…
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3.5 w-3.5" />
                      Draft Response
                    </>
                  )}
                </Button>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2 pt-0">
              {q.answer ? (
                <>
                  <div className="whitespace-pre-wrap rounded-md bg-muted/50 p-4 text-sm leading-relaxed">
                    {q.answer.content}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {q.answer.generatedBy ? `Generated by ${q.answer.generatedBy}` : 'Manual draft'}
                    {' · '}
                    Updated {new Date(q.answer.updatedAt).toLocaleString()}
                  </div>
                </>
              ) : (
                <p className="text-sm text-muted-foreground">No draft yet.</p>
              )}
              {error && (
                <p className="text-xs text-destructive" data-testid={`draft-error-${q.id}`}>
                  {error}
                </p>
              )}
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
